# Generated by Django 4.1.5 on 2023-01-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillas', '0002_zapatillas_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='entregado',
            field=models.CharField(max_length=100),
        ),
    ]
