# Generated by Django 4.1.5 on 2023-01-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillas', '0003_alter_entrega_entregado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='entregado',
            new_name='entrega',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='name',
        ),
    ]
