# Generated by Django 4.1.5 on 2023-02-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillas', '0005_rename_entrega_entrega_estado_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='imagen',
            field=models.ImageField(null=True, upload_to='tareas'),
        ),
    ]
